name: Merge Workflow

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Publish
        uses: 24dlong/github-actions-library/actions/publish@v5
        with:
          # requried to bypass branch protection
          GITHUB_WORKFLOWS_CLIENT_ID: ${{ vars.GH_WORKFLOWS_APP_CLIENT_ID }}
          GITHUB_WORKFLOWS_PRIVATE_KEY: ${{ secrets.GH_WORKFLOWS_APP_PRIVATE_KEY }}
