name: Merge Workflow

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Publish
        uses: 24dlong/github-actions-library/actions/publish@v3
        with:
          # required to bypass branch protection in user-owned repositories
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
