name: Pull Request Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  quality-gate:
    runs-on: ubuntu-latest
    name: Quality Gate | Core
    steps:
      - name: Set up Python
        uses: actions/setup-python@v7

      - uses: 24dlong/github-actions-library/actions/quality-gate@v3
